# Mosquitto MQTT Broker Configuration
# Used by G2 Ingestion Service and G1 GPS devices

# Default MQTT listener
listener 1883
allow_anonymous true #true for local dev only - we will use auth for production 

# WebSocket listener (useful for browser-based MQTT debugging tools)
# For testing purposes only
listener 9001             
protocol websockets

# Logging
log_dest stdout # Prints logs to stdout 
log_type all  # All logging for debugging # We will tune this for production log_type error log_type warning log_type notice log_type debug

# Persistence
persistence true # Required for production to persist messages across restarts If broker restarts, it can remeber which buses subscribed to which topics and deliver messages accordingly
persistence_location /mosquitto/data/ # Directory where messages are persisted # Will be removed in production
